# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlutterTest

  target 'FlutterTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterTestUITests' do
    # Pods for testing
  end
  
    flutter_application_path = '/Users/mananvij/Documents/swift-apps/FlutterTest/my_flutter'
    load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

      install_all_flutter_pods(flutter_application_path)


    post_install do |installer|
      flutter_post_install(installer) if defined?(flutter_post_install)
    end

end
