//
//  ImagePresenter.swift
//  imageVIP
//
//  Created by Manan Vij on 16/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImagePresentationLogic
{
  func presentAPI(response: Image.ImageAPI.Response)
}

class ImagePresenter: ImagePresentationLogic
{
  weak var viewController: ImageDisplayLogic?
  
  // MARK: Do API
  
  func presentAPI(response: Image.ImageAPI.Response)
  {
      if response.success {
          let viewModel = Image.ImageAPI.ViewModel(url: response.url)
          viewController?.displayAPI(viewModel: viewModel)
      }
  }
}
