//
//  ImageModels.swift
//  imageVIP
//
//  Created by Manan Vij on 16/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Image
{
    // MARK: Use cases
    
    enum ImageAPI
    {
        struct Request
        {
        }
        struct Response
        {
            let success: Bool
            let msg: String
            let url: [URLs]
        }
        struct ViewModel
        {
            let url: [URLs]
        }
    }
}
